import js from '@eslint/js'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import globals from 'globals'
import tseslint from 'typescript-eslint'

export default tseslint.config(
    {
        // Generated by wails and by the build; nothing here is written by hand.
        ignores: ['dist', 'wailsjs', 'node_modules'],
    },
    {
        files: ['**/*.{ts,tsx}'],
        extends: [js.configs.recommended, ...tseslint.configs.recommended],
        languageOptions: {
            ecmaVersion: 2022,
            globals: globals.browser,
        },
        plugins: {
            'react-hooks': reactHooks,
            'react-refresh': reactRefresh,
        },
        rules: {
            ...reactHooks.configs.recommended.rules,

            // The rule this project was installed for. A hook that reads a
            // value but does not list it keeps showing the value it saw the
            // first time — which is invisible until something goes stale, and
            // has already cost this codebase one bug in workspaces-store.
            'react-hooks/exhaustive-deps': 'error',

            // Fast Refresh can only replace a module that exports components
            // and nothing else. Warn, because a few files here deliberately
            // export a hook beside its provider.
            'react-refresh/only-export-components': [
                'warn',
                {allowConstantExport: true},
            ],

            // An unused variable is usually a leftover. The exception is the
            // deliberate placeholder, spelled with a leading underscore.
            '@typescript-eslint/no-unused-vars': [
                'error',
                {
                    argsIgnorePattern: '^_',
                    varsIgnorePattern: '^_',
                    caughtErrorsIgnorePattern: '^_',
                },
            ],
        },
    },
)
