// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';
import {files} from '../models';
import {transport} from '../models';
import {session} from '../models';

export function CancelTransfer(arg1:string):Promise<void>;

export function CheckSSMTools():Promise<void>;

export function ClearWorkspaceAWSSecret(arg1:string):Promise<void>;

export function ConnectSession(arg1:string,arg2:string,arg3:number,arg4:number):Promise<string>;

export function CreateConnection(arg1:string,arg2:store.ConnectionInput):Promise<store.Connection>;

export function CreateWorkspace(arg1:store.WorkspaceInput):Promise<store.Workspace>;

export function DeleteConnection(arg1:string):Promise<void>;

export function DeleteConnectionPassword(arg1:string):Promise<void>;

export function DeleteSetting(arg1:string):Promise<void>;

export function DeleteWorkspace(arg1:string):Promise<void>;

export function DisconnectSession(arg1:string):Promise<void>;

export function DownloadFile(arg1:string,arg2:string):Promise<files.Transfer>;

export function ExportSessionLog(arg1:store.SessionLogFilter,arg2:string):Promise<string>;

export function GetAllSettings():Promise<Record<string, string>>;

export function GetConnection(arg1:string):Promise<store.Connection>;

export function GetWorkspace(arg1:string):Promise<store.Workspace>;

export function HasConnectionPassword(arg1:string):Promise<boolean>;

export function HasWorkspaceAWSSecret(arg1:string):Promise<boolean>;

export function HostKeyQuestion(arg1:string):Promise<transport.HostKeyPrompt>;

export function ImportAWSFromShell(arg1:string):Promise<void>;

export function ListConnections(arg1:string):Promise<Array<store.Connection>>;

export function ListRemoteDirectory(arg1:string,arg2:string):Promise<files.Listing>;

export function ListSessionLog(arg1:store.SessionLogFilter):Promise<Array<store.SessionLogEntry>>;

export function ListTransfers():Promise<Array<files.Transfer>>;

export function ListWorkspaces():Promise<Array<store.Workspace>>;

export function MoveConnection(arg1:string,arg2:string):Promise<void>;

export function OpenSessions():Promise<Array<session.Info>>;

export function ParseSSHCommand(arg1:string):Promise<store.ParsedSSHCommand>;

export function PreviewAWSFromShell():Promise<transport.AWSShellPreview>;

export function ReorderWorkspaces(arg1:Array<string>):Promise<void>;

export function ResizeSession(arg1:string,arg2:number,arg3:number):Promise<void>;

export function ResolveAWSForConnection(arg1:string):Promise<store.ResolvedAWS>;

export function SetConnectionPassword(arg1:string,arg2:string):Promise<void>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;

export function SetWorkspaceAWSSecret(arg1:string,arg2:string,arg3:string):Promise<void>;

export function TrustHostKey(arg1:string):Promise<void>;

export function UpdateConnection(arg1:string,arg2:store.ConnectionInput):Promise<store.Connection>;

export function UpdateWorkspace(arg1:string,arg2:store.WorkspaceInput):Promise<store.Workspace>;

export function UploadFiles(arg1:string,arg2:string):Promise<Array<files.Transfer>>;

export function WriteToSession(arg1:string,arg2:string):Promise<void>;
