// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';

export function CheckSSMTools():Promise<void>;

export function ConnectSession(arg1:string,arg2:string,arg3:number,arg4:number):Promise<void>;

export function CreateConnection(arg1:string,arg2:store.ConnectionInput):Promise<store.Connection>;

export function CreateWorkspace(arg1:store.WorkspaceInput):Promise<store.Workspace>;

export function DeleteConnection(arg1:string):Promise<void>;

export function DeleteConnectionPassword(arg1:string):Promise<void>;

export function DeleteWorkspace(arg1:string):Promise<void>;

export function DisconnectSession(arg1:string):Promise<void>;

export function GetConnection(arg1:string):Promise<store.Connection>;

export function GetWorkspace(arg1:string):Promise<store.Workspace>;

export function HasConnectionPassword(arg1:string):Promise<boolean>;

export function ListConnections(arg1:string):Promise<Array<store.Connection>>;

export function ListWorkspaces():Promise<Array<store.Workspace>>;

export function MoveConnection(arg1:string,arg2:string):Promise<void>;

export function OpenSessionIDs():Promise<Array<string>>;

export function ParseSSHCommand(arg1:string):Promise<store.ParsedSSHCommand>;

export function ReorderWorkspaces(arg1:Array<string>):Promise<void>;

export function ResizeSession(arg1:string,arg2:number,arg3:number):Promise<void>;

export function ResolveAWSForConnection(arg1:string):Promise<store.ResolvedAWS>;

export function SetConnectionPassword(arg1:string,arg2:string):Promise<void>;

export function UpdateConnection(arg1:string,arg2:store.ConnectionInput):Promise<store.Connection>;

export function UpdateWorkspace(arg1:string,arg2:store.WorkspaceInput):Promise<store.Workspace>;

export function WriteToSession(arg1:string,arg2:string):Promise<void>;
