// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckSSMTools() {
  return window['go']['main']['App']['CheckSSMTools']();
}

export function ConnectSession(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ConnectSession'](arg1, arg2, arg3, arg4);
}

export function CreateConnection(arg1, arg2) {
  return window['go']['main']['App']['CreateConnection'](arg1, arg2);
}

export function CreateWorkspace(arg1) {
  return window['go']['main']['App']['CreateWorkspace'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function DeleteConnectionPassword(arg1) {
  return window['go']['main']['App']['DeleteConnectionPassword'](arg1);
}

export function DeleteWorkspace(arg1) {
  return window['go']['main']['App']['DeleteWorkspace'](arg1);
}

export function DisconnectSession(arg1) {
  return window['go']['main']['App']['DisconnectSession'](arg1);
}

export function GetConnection(arg1) {
  return window['go']['main']['App']['GetConnection'](arg1);
}

export function GetWorkspace(arg1) {
  return window['go']['main']['App']['GetWorkspace'](arg1);
}

export function HasConnectionPassword(arg1) {
  return window['go']['main']['App']['HasConnectionPassword'](arg1);
}

export function ListConnections(arg1) {
  return window['go']['main']['App']['ListConnections'](arg1);
}

export function ListWorkspaces() {
  return window['go']['main']['App']['ListWorkspaces']();
}

export function MoveConnection(arg1, arg2) {
  return window['go']['main']['App']['MoveConnection'](arg1, arg2);
}

export function OpenSessionIDs() {
  return window['go']['main']['App']['OpenSessionIDs']();
}

export function ParseSSHCommand(arg1) {
  return window['go']['main']['App']['ParseSSHCommand'](arg1);
}

export function ReorderWorkspaces(arg1) {
  return window['go']['main']['App']['ReorderWorkspaces'](arg1);
}

export function ResizeSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeSession'](arg1, arg2, arg3);
}

export function ResolveAWSForConnection(arg1) {
  return window['go']['main']['App']['ResolveAWSForConnection'](arg1);
}

export function SetConnectionPassword(arg1, arg2) {
  return window['go']['main']['App']['SetConnectionPassword'](arg1, arg2);
}

export function UpdateConnection(arg1, arg2) {
  return window['go']['main']['App']['UpdateConnection'](arg1, arg2);
}

export function UpdateWorkspace(arg1, arg2) {
  return window['go']['main']['App']['UpdateWorkspace'](arg1, arg2);
}

export function WriteToSession(arg1, arg2) {
  return window['go']['main']['App']['WriteToSession'](arg1, arg2);
}
